### ISSUE TITLE
Disable `Ctrl + Enter` shortcut to complete task

### ISSUE THREAD

**Issue by mchernosky** [gitusp/asana-extra-key-mappings#2]
Hey thanks for this extension... it makes it possible to avoid the mouse when editing tasks.

Another minor keyboard shortcut issue is that that `Ctrl +`Enter` completes a task, however I am soooo used to using this shortcut to finish entering some text. I'm constantly, accidentally completing tasks.

It would be nice to disable `Ctrl + Enter` as a shortcut for completing a task.

**Comment by gitusp** [comment]
Hi @mchernosky, thanks for the feature request.
It makes sense to add an option to disable the shortcut, I confirmed that certain amount of people face the issue: https://forum.asana.com/t/support-shift-enter-for-line-breaks/55963/7

I'll give a shot soon. :)

**Comment by gitusp** [comment]
I confirmed that Asana's shortcut is bound to `keydown` of `document`.
I'm trying to inject `ctrl+enter` preventer **before** them.

**Comment by gitusp** [comment]
Confirmed that simply injecting the below event listener to `document.body` and do `stopPropagation` in the handler works.

```
document.body.addEventListener('keydown', (e) => {
  if (e.keyCode === 13 && (e.metaKey || e.ctrlKey)) { e.stopPropagation(); }   
});
```

**Comment by gitusp** [comment]
I've just submitted the new version. The new version is now being reviewed.
If there's nothing, it will be published in a few days.

**Comment by gitusp** [comment]
I've added an option view like this:
<img width="1552" alt="Screen Shot 2022-02-09 at 20 48 07" src="https://user-images.githubusercontent.com/2055516/153194132-2a099aed-b17c-4064-9494-1b9bb3c08eba.png">

**Comment by gitusp** [comment]
https://chrome.google.com/webstore/detail/asana-extra-key-mappings/kggmcmncpcohaknajapmmfchmlhegook?hl=en
Published 🎉
